version: "3.9"

services:
  fogindex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - shared-repos:/shared/repos
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - app-network

  middleware:
    build:
      context: .
      dockerfile: DockerfileMiddleware
    ports:
      - "5000:5000"
    volumes:
      - shared-repos:/shared/repos
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-repos:
